name: ${project.artifactId}
main: com.mcmiddleearth.mcme.pvpplugin.PVPPlugin
version: ${project.version}
authors: [NicoviçTheSixth,Johnyeric]
depend: [WorldEdit]
api-version: 1.19

commands:
  MapEditor:
    description: edit/create new pvp maps
    usage: /mapedit <arguments>
  Locker:
    description: lock/unlock pvp server and/or kick people
    usage: /locker <arguments>
  PVP:
    description: main command used for running pvp
    usage: /pvp <arguments>
  T:
    description: team chat command
    usage: /t <message>

  permissions:
    pvp.gameCanRun:
      description: Can run games on pvp server.
      default: op
    pvp.mapEditor:
      description: Can create/edit maps on pvp server.
      default: op
    pvp.adminPermission:
      description: Can do everything with the pvp plugin.
      default: op
    pvp.manager:
      children:
        pvp.gameCanRun: true
    pvp.admin:
      children:
        pvp.mapEditor: true
        pvp.manager: true
        pvp.adminPermission: true
